services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ansible
    stdin_open: true
    env_file:
      - .env
    network_mode: host
    tty: true
    volumes:
      - ./roles:/roles
    working_dir: /roles