services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ansible
    stdin_open: true
    env_file:
      - .env
    network_mode: host
    tty: true
    volumes:
    - .:/workdir
    - ./templates/harbor.yml.j2:/root/.ansible/roles/robertdebock.harbor/templates/harbor.yml.j2
    working_dir: /workdir