- name: Ensure group exists
  group:
    name: "{{ runner_group }}"
    state: present

- name: Ensure user exists
  user:
    name: "{{ runner_user }}"
    group: "{{ runner_group }}"
    home: "{{ runner_home }}"
    state: present
    groups: sudo
    append: yes

- name: Add runner user to docker group
  user:
    name: "{{ runner_user }}"
    groups: docker
    append: yes

- name: Ensure github-actions-runner uses bash
  user:
    name: "{{ runner_user }}"
    shell: /bin/bash
  
- name: Download GitHub Actions software
  get_url:
    url: "{{ runner_url }}"
    dest: "/home/{{ runner_user }}/{{ runner_package }}"
    mode: "0600"
    owner: "{{ runner_user }}"
    group: "{{ runner_group }}"
    checksum: "{{ runner_checksum }}"
  become: true
  become_user: "{{ runner_user }}"

- name: Create directory for extracted runner
  file:
    dest: "{{ runner_home }}/actions-runner"
    owner: "{{ runner_user }}"
    group: "{{ runner_group }}"
    state: directory
  become_user: "{{ runner_user }}"

- name: Extract GitHub Actions runner
  unarchive:
    src: "{{ runner_home }}/{{ runner_package }}"
    remote_src: true
    dest: "{{ runner_home }}/actions-runner"
    owner: "{{ runner_user }}"
    group: "{{ runner_group }}"
    creates: "{{ runner_home }}/actions-runner/bin/Run.Listener"
  become_user: "{{ runner_user }}"

- name: Check if runner already configured
  stat:
    path: "{{ runner_home }}/actions-runner/.credentials"
  register: runner_credentials_file
  become_user: "{{ runner_user }}"

- name: Configure GitHub Actions self-hosted runner
  shell: |
    ./config.sh \
      --url {{ repo_url }} \
      --pat '{{ lookup("env", "GITHUB_PAT") }}' \
      --name {{ runner_name }} \
      --labels '{{ runner_labels }}' \
      --unattended \
      --replace
  args:
    chdir: "{{ runner_home }}/actions-runner/"
  when: not runner_credentials_file.stat.exists
  no_log: true
  become_user: "{{ runner_user }}"

- name: Install runner systemd service
  template:
    src: "{{ workdir_service }}"
    dest: "{{ runner_service }}"
    owner: root
    group: root
    mode: "0644"

- name: Start GitHub Actions runner service
  service:
    name: "{{ runner_user }}-runner.service"
    state: started
    enabled: yes
    daemon_reload: true
