- name: Ensure Docker is installed
  package:
    name: docker.io
    state: present

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: true

- name: Get Docker version
  command: docker --version
  register: docker_version

- name: Show Docker version
  debug:
    var: docker_version.stdout

- name: Ensure Docker Compose is installed
  package:
    name: docker-compose
    state: present

- name: Get Docker Compose version
  command: docker-compose --version
  register: docker_compose_version
  changed_when: false

- name: Show Docker Compose version
  debug:
    var: docker_compose_version.stdout